/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTrips"];
        put?: never;
        post: operations["CreateTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTrip"];
        put?: never;
        post?: never;
        delete: operations["DeleteTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/participants/{pid}/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateParticipantPrefs"];
        trace?: never;
    };
    "/trips/{tripId}/participants/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RemoveParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Optimise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/runs/{runId}/pareto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetParetoSolutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/lock-solution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LockSolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/whatif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WhatIf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/cost-split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CostSplit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/return-leg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReturnLeg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddParticipantRequest: {
            displayName: string;
            homeAddress: null | string;
            /** Format: double */
            homeLongitude: null | number | string;
            /** Format: double */
            homeLatitude: null | number | string;
            hasCar: boolean;
            /** Format: int32 */
            seats: number | string;
            preferences: null | components["schemas"]["PreferencesDto"];
        };
        AuthTokenResponse: {
            accessToken: string;
            refreshToken: string;
            /** Format: date-time */
            expiresAt: string;
            userId: string;
            email: string;
            displayName: string;
        };
        CostSplitEntry: {
            /** Format: uuid */
            participantId: string;
            displayName: string;
            /** Format: double */
            share: number | string;
            /** Format: double */
            kilometres: number | string;
        };
        CostSplitResponse: {
            /** Format: uuid */
            tripId: string;
            /** Format: uuid */
            solutionId: null | string;
            entries: components["schemas"]["CostSplitEntry"][];
            /** Format: double */
            totalCost: number | string;
            todo: null | string;
        };
        CreateTripRequest: {
            name: string;
            destinationName: string;
            /** Format: double */
            destinationLongitude: number | string;
            /** Format: double */
            destinationLatitude: number | string;
            /** Format: date-time */
            departAt: string;
            /** Format: date-time */
            arrivalWindowEarliest: string;
            /** Format: date-time */
            arrivalWindowLatest: string;
        };
        DriverRouteDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            driverId: string;
            /** Format: double */
            travelMins: number | string;
            /** Format: int32 */
            orderIndex: number | string;
            stops: components["schemas"]["StopDto"][];
        };
        EnqueueRunResponse: {
            /** Format: uuid */
            runId: string;
        };
        LockSolutionRequest: {
            /** Format: uuid */
            runId: string;
            /** Format: int32 */
            paretoIndex: number | string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        ObjectiveWeightsDto: {
            /** Format: double */
            driveTime: number | string;
            /** Format: double */
            stopCount: number | string;
            /** Format: double */
            walkAndPt: number | string;
            /** Format: double */
            arrivalSpread: number | string;
            /** Format: double */
            fairness: number | string;
        };
        OptimisationRunDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            status: components["schemas"]["OptimisationStatus"];
            solver: components["schemas"]["SolverKind"];
            weights: components["schemas"]["ObjectiveWeightsDto"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: null | string;
            failureReason: null | string;
            /** Format: uuid */
            bestSolutionId: null | string;
            stats: null | components["schemas"]["OptimisationStatsDto"];
        };
        OptimisationRunDtoWithSolution: {
            run: components["schemas"]["OptimisationRunDto"];
            solution: null | components["schemas"]["SolutionDto"];
        };
        OptimisationStatsDto: {
            wallClock: string;
            /** Format: int32 */
            iterationsOrNodes: number | string;
            /** Format: double */
            bestObjective: number | string;
            /** Format: double */
            lpRelaxation: null | number | string;
            solver: components["schemas"]["SolverKind"];
        };
        OptimisationStatus: number;
        OptimiseRequest: {
            weights: components["schemas"]["ObjectiveWeightsDto"];
            solver?: components["schemas"]["SolverKind"];
        };
        ParticipantDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            /** Format: uuid */
            userId: string;
            displayName: string;
            /** Format: double */
            homeLongitude: number | string;
            /** Format: double */
            homeLatitude: number | string;
            hasCar: boolean;
            /** Format: int32 */
            seats: number | string;
            preferences: components["schemas"]["PreferencesDto"];
        };
        PreferencesDto: {
            /** Format: int32 */
            walkBudgetMins: number | string;
            /** Format: int32 */
            detourToleranceMins: number | string;
            /** Format: double */
            fairnessWeight: number | string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
        };
        SolutionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            optimisationRunId: string;
            label: string;
            /** Format: double */
            objective: number | string;
            objectiveTerms: (number | string)[];
            routes: components["schemas"]["DriverRouteDto"][];
        };
        /** @default 0 */
        SolverKind: number;
        StopDto: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            orderIndex: number | string;
            /** Format: double */
            longitude: number | string;
            /** Format: double */
            latitude: number | string;
            /** Format: uuid */
            candidateNodeId: string;
            /** Format: date-time */
            estimatedArrival: string;
            pickups: string[];
        };
        TripDto: {
            /** Format: uuid */
            id: string;
            name: string;
            destinationName: string;
            /** Format: double */
            destinationLongitude: number | string;
            /** Format: double */
            destinationLatitude: number | string;
            /** Format: date-time */
            departAt: string;
            /** Format: date-time */
            arrivalWindowEarliest: string;
            /** Format: date-time */
            arrivalWindowLatest: string;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            lockedSolutionId: null | string;
        };
        WhatIfRequest: {
            dropParticipantIds: null | string[];
            addParticipants: null | components["schemas"]["AddParticipantRequest"][];
            newWeights: null | components["schemas"]["ObjectiveWeightsDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    Login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    Refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
        };
    };
    ListTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"][];
                };
            };
        };
    };
    CreateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
        };
    };
    GetTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddParticipantRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateParticipantPrefs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RemoveParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Optimise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimiseRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimisationRunDtoWithSolution"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetParetoSolutions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionDto"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LockSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockSolutionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatIf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CostSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSplitResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReturnLeg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
