/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/refresh-candidate-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["RefreshCandidateNodes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTrips"];
        put?: never;
        post: operations["CreateTrip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetTrip"];
        put?: never;
        post?: never;
        delete: operations["DeleteTrip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{id}/destination": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateTripDestination"];
        trace?: never;
    };
    "/trips/{tripId}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AddParticipant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/participants/{pid}/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UpdateParticipantPrefs"];
        trace?: never;
    };
    "/trips/{tripId}/participants/{pid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["RemoveParticipant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/optimise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["Optimise"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/runs/{runId}/pareto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetParetoSolutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/lock-solution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["LockSolution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/locked-solution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["GetLockedSolution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/whatif": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WhatIf"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/cost-split": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CostSplit"];
        put?: never;
        post: operations["CostSplitWithInputs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/return-leg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ReturnLeg"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/participants/{participantId}/calendar.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ParticipantCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/trips/{tripId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ListTripEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddParticipantRequest: {
            displayName: string;
            homeAddress: null | string;
            /** Format: double */
            homeLongitude: null | number | string;
            /** Format: double */
            homeLatitude: null | number | string;
            hasCar: boolean;
            /** Format: int32 */
            seats: number | string;
            preferences: null | components["schemas"]["PreferencesDto"];
        };
        CandidateNodeDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            participantId: string;
            kind: components["schemas"]["CandidateNodeKindDto"];
            /** Format: double */
            longitude: number | string;
            /** Format: double */
            latitude: number | string;
            /** Format: int32 */
            walkMins: number | string;
            /** Format: int32 */
            ptMins: number | string;
            externalId: null | string;
            displayName: null | string;
            path: null | components["schemas"]["PathDto"];
        };
        /** @enum {unknown} */
        CandidateNodeKindDto: "home" | "trainStation" | "busStop" | "wharf" | "lightRailStop";
        CostSplitEntry: {
            /** Format: uuid */
            participantId: string;
            displayName: string;
            /** Format: double */
            fuelShare: number | string;
            /** Format: double */
            tollShare: number | string;
            /** Format: double */
            total: number | string;
        };
        CostSplitInputsDto: {
            /** Format: double */
            fuelPricePerLitre: null | number | string;
            /** Format: double */
            fuelEconomyLPer100Km: null | number | string;
            tolls: null | components["schemas"]["TollSegmentDto"][];
        };
        CostSplitResponse: {
            /** Format: uuid */
            tripId: string;
            /** Format: uuid */
            solutionId: null | string;
            entries: components["schemas"]["CostSplitEntry"][];
            /** Format: double */
            totalCost: number | string;
            /** Format: double */
            totalFuel: number | string;
            /** Format: double */
            totalTolls: number | string;
            /** Format: double */
            fuelPricePerLitre: number | string;
            /** Format: double */
            fuelEconomyLPer100Km: number | string;
        };
        CreateTripRequest: {
            name: string;
            destinationName: string;
            /** Format: double */
            destinationLongitude: number | string;
            /** Format: double */
            destinationLatitude: number | string;
            /** Format: date-time */
            departAt: string;
            /** Format: date-time */
            arrivalWindowEarliest: string;
            /** Format: date-time */
            arrivalWindowLatest: string;
        };
        DriverRouteDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            driverId: string;
            /** Format: double */
            travelMins: number | string;
            /** Format: int32 */
            orderIndex: number | string;
            stops: components["schemas"]["StopDto"][];
            /** Format: date-time */
            destinationArrival?: null | string;
            /** Format: date-time */
            departure?: null | string;
        };
        EnqueueRunResponse: {
            /** Format: uuid */
            runId: string;
        };
        /** @enum {unknown} */
        EventKind: "tripCreated" | "participantAdded" | "participantRemoved" | "optimisationStarted" | "optimisationCompleted" | "optimisationFailed" | "solutionLocked" | "driverDeparted" | "driverPositionUpdated" | "driverLate" | "passengerAtStop" | "routeRecomputed";
        LockSolutionRequest: {
            /** Format: uuid */
            runId: string;
            /** Format: int32 */
            paretoIndex: number | string;
        };
        ObjectiveWeightsDto: {
            /** Format: double */
            driveTime: number | string;
            /** Format: double */
            stopCount: number | string;
            /** Format: double */
            walkAndPt: number | string;
            /** Format: double */
            arrivalSpread: number | string;
            /** Format: double */
            fairness: number | string;
        };
        OptimisationRunDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            status: components["schemas"]["OptimisationStatus"];
            solver: components["schemas"]["SolverKind"];
            weights: components["schemas"]["ObjectiveWeightsDto"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: null | string;
            failureReason: null | string;
            /** Format: uuid */
            bestSolutionId: null | string;
            stats: null | components["schemas"]["OptimisationStatsDto"];
        };
        OptimisationRunDtoWithSolution: {
            run: components["schemas"]["OptimisationRunDto"];
            solution: null | components["schemas"]["SolutionDto"];
        };
        OptimisationStatsDto: {
            wallClock: string;
            /** Format: int32 */
            iterationsOrNodes: number | string;
            /** Format: double */
            bestObjective: number | string;
            /** Format: double */
            lpRelaxation: null | number | string;
            solver: components["schemas"]["SolverKind"];
        };
        /** @enum {unknown} */
        OptimisationStatus: "pending" | "running" | "completed" | "failed" | "cancelled";
        OptimiseRequest: {
            weights: components["schemas"]["ObjectiveWeightsDto"];
            solver?: components["schemas"]["SolverKind"];
        };
        ParticipantDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            displayName: string;
            /** Format: double */
            homeLongitude: number | string;
            /** Format: double */
            homeLatitude: number | string;
            hasCar: boolean;
            /** Format: int32 */
            seats: number | string;
            preferences: components["schemas"]["PreferencesDto"];
        };
        ParticipantWithNodesDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            displayName: string;
            /** Format: double */
            homeLongitude: number | string;
            /** Format: double */
            homeLatitude: number | string;
            hasCar: boolean;
            /** Format: int32 */
            seats: number | string;
            preferences: components["schemas"]["PreferencesDto"];
            candidateNodes: components["schemas"]["CandidateNodeDto"][];
        };
        PathCoordinateDto: {
            /** Format: double */
            longitude: number | string;
            /** Format: double */
            latitude: number | string;
        };
        PathDto: {
            coordinates: components["schemas"]["PathCoordinateDto"][];
        };
        PathLegDto: {
            mode: string;
            path: components["schemas"]["PathDto"];
            /**
             * Format: int32
             * @default 0
             */
            durationMins: number | string;
            fromName?: null | string;
            toName?: null | string;
            routeShortName?: null | string;
            /** Format: date-time */
            departureTime?: null | string;
            /** Format: date-time */
            arrivalTime?: null | string;
        };
        PickupLegDto: {
            /** Format: uuid */
            participantId: string;
            /** Format: int32 */
            walkMins: number | string;
            /** Format: int32 */
            ptMins: number | string;
            path: null | components["schemas"]["PathDto"];
            pathLegs?: null | components["schemas"]["PathLegDto"][];
        };
        PreferencesDto: {
            /** Format: int32 */
            walkBudgetMins: number | string;
            /** Format: int32 */
            detourToleranceMins: number | string;
            /** Format: double */
            fairnessWeight: number | string;
        };
        RefreshCandidateNodesResponse: {
            /** Format: int32 */
            participantsRefreshed: number | string;
            /** Format: int32 */
            candidateNodesBefore: number | string;
            /** Format: int32 */
            candidateNodesAfter: number | string;
        };
        ReturnLegRequest: {
            requests: components["schemas"]["ReturnRequestDto"][];
        };
        ReturnLegResponse: {
            solutions: components["schemas"]["SolutionDto"][];
        };
        ReturnRequestDto: {
            /** Format: uuid */
            participantId: string;
            /** Format: date-time */
            desiredDeparture: string;
            /** Format: double */
            dropoffLongitude: number | string;
            /** Format: double */
            dropoffLatitude: number | string;
        };
        SolutionDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            optimisationRunId: string;
            label: string;
            /** Format: double */
            objective: number | string;
            objectiveTerms: (number | string)[];
            routes: components["schemas"]["DriverRouteDto"][];
        };
        /**
         * @default orTools
         * @enum {unknown}
         */
        SolverKind: "orTools" | "heuristic";
        StopDto: {
            /** Format: uuid */
            id: string;
            /** Format: int32 */
            orderIndex: number | string;
            /** Format: double */
            longitude: number | string;
            /** Format: double */
            latitude: number | string;
            /** Format: uuid */
            candidateNodeId: string;
            nodeKind: components["schemas"]["CandidateNodeKindDto"];
            /** Format: date-time */
            estimatedArrival: string;
            pickups: components["schemas"]["PickupLegDto"][];
        };
        TollSegmentDto: {
            /** Format: uuid */
            fromStopId: string;
            /** Format: uuid */
            toStopId: string;
            /** Format: double */
            amount: number | string;
        };
        TripDetailDto: {
            /** Format: uuid */
            id: string;
            name: string;
            destinationName: string;
            /** Format: double */
            destinationLongitude: number | string;
            /** Format: double */
            destinationLatitude: number | string;
            /** Format: date-time */
            departAt: string;
            /** Format: date-time */
            arrivalWindowEarliest: string;
            /** Format: date-time */
            arrivalWindowLatest: string;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            lockedSolutionId: null | string;
            participants: components["schemas"]["ParticipantWithNodesDto"][];
        };
        TripDto: {
            /** Format: uuid */
            id: string;
            name: string;
            destinationName: string;
            /** Format: double */
            destinationLongitude: number | string;
            /** Format: double */
            destinationLatitude: number | string;
            /** Format: date-time */
            departAt: string;
            /** Format: date-time */
            arrivalWindowEarliest: string;
            /** Format: date-time */
            arrivalWindowLatest: string;
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: uuid */
            lockedSolutionId: null | string;
            /** Format: int32 */
            participantCount: number | string;
        };
        TripEventDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tripId: string;
            kind: components["schemas"]["EventKind"];
            /** Format: uuid */
            actorId: null | string;
            /** Format: double */
            longitude: null | number | string;
            /** Format: double */
            latitude: null | number | string;
            /** Format: date-time */
            timestamp: string;
            payloadJson: null | string;
        };
        UpdateTripDestinationRequest: {
            destinationName: string;
            /** Format: double */
            destinationLongitude: number | string;
            /** Format: double */
            destinationLatitude: number | string;
        };
        WhatIfRequest: {
            dropParticipantIds: null | string[];
            addParticipants: null | components["schemas"]["AddParticipantRequest"][];
            newWeights: null | components["schemas"]["ObjectiveWeightsDto"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RefreshCandidateNodes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshCandidateNodesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListTrips: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"][];
                };
            };
        };
    };
    CreateTrip: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
        };
    };
    GetTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteTrip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateTripDestination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripDestinationRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AddParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddParticipantRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    UpdateParticipantPrefs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                pid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferencesDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    RemoveParticipant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                pid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Optimise: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimiseRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimisationRunDtoWithSolution"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetParetoSolutions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionDto"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    LockSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LockSolutionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetLockedSolution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionDto"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WhatIf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WhatIfRequest"];
            };
        };
        responses: {
            /** @description Accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnqueueRunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CostSplit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSplitResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CostSplitWithInputs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["CostSplitInputsDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CostSplitResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReturnLeg: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["ReturnLegRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReturnLegResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ParticipantCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tripId: string;
                participantId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ListTripEvents: {
        parameters: {
            query?: {
                since?: string;
            };
            header?: never;
            path: {
                tripId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripEventDto"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
