// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trips.Data;

#nullable disable

namespace Trips.Data.Migrations
{
    [DbContext(typeof(TripsDbContext))]
    [Migration("20260523200751_CandidateNodePath")]
    partial class CandidateNodePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trips.Core.Domain.CandidateNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<LineString>("Path")
                        .HasColumnType("geometry(LineString, 4326)");

                    b.Property<int>("PtMins")
                        .HasColumnType("integer");

                    b.Property<int>("WalkMins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("ParticipantId");

                    b.ToTable("candidate_nodes", (string)null);
                });

            modelBuilder.Entity("Trips.Core.Domain.DriverRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SolutionId")
                        .HasColumnType("uuid");

                    b.Property<double>("TravelMins")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("SolutionId");

                    b.HasIndex("SolutionId", "OrderIndex");

                    b.ToTable("driver_routes", (string)null);
                });

            modelBuilder.Entity("Trips.Core.Domain.OptimisationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BestObjective")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("BestSolutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("IterationsOrNodes")
                        .HasColumnType("integer");

                    b.Property<double?>("LpRelaxation")
                        .HasColumnType("double precision");

                    b.Property<int>("Solver")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("WallClock")
                        .HasColumnType("interval");

                    b.Property<double>("WeightArrivalSpread")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightDriveTime")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightFairness")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightStopCount")
                        .HasColumnType("double precision");

                    b.Property<double>("WeightWalkAndPt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId", "StartedAt");

                    b.ToTable("optimisation_runs", (string)null);
                });

            modelBuilder.Entity("Trips.Core.Domain.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DetourToleranceMins")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double>("FairnessWeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("HasCar")
                        .HasColumnType("boolean");

                    b.Property<Point>("Home")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<int>("Seats")
                        .HasColumnType("integer");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.Property<int>("WalkBudgetMins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Home");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Home"), "gist");

                    b.HasIndex("TripId");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Trips.Core.Domain.Solution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<double>("Objective")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<double[]>("ObjectiveTerms")
                        .IsRequired()
                        .HasColumnType("double precision[]");

                    b.Property<Guid>("OptimisationRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OptimisationRunId");

                    b.ToTable("solutions", (string)null);
                });

            modelBuilder.Entity("Trips.Core.Domain.Stop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CandidateNodeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DriverRouteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EstimatedArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<Guid[]>("Pickups")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.HasIndex("DriverRouteId");

                    b.HasIndex("DriverRouteId", "OrderIndex");

                    b.ToTable("stops", (string)null);
                });

            modelBuilder.Entity("Trips.Core.Domain.Trip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ArrivalWindowEarliest")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ArrivalWindowLatest")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DepartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("DestinationLocation")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("LockedSolutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DestinationLocation");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DestinationLocation"), "gist");

                    b.HasIndex("OwnerId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Trips.Core.Domain.TripEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TripId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.HasIndex("TripId", "Timestamp");

                    b.ToTable("trip_events", (string)null);
                });

            modelBuilder.Entity("Trips.Core.Domain.CandidateNode", b =>
                {
                    b.HasOne("Trips.Core.Domain.Participant", null)
                        .WithMany("CandidateNodes")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Core.Domain.DriverRoute", b =>
                {
                    b.HasOne("Trips.Core.Domain.Solution", null)
                        .WithMany("Routes")
                        .HasForeignKey("SolutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Core.Domain.OptimisationRun", b =>
                {
                    b.HasOne("Trips.Core.Domain.Trip", null)
                        .WithMany("Runs")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Core.Domain.Participant", b =>
                {
                    b.HasOne("Trips.Core.Domain.Trip", null)
                        .WithMany("Participants")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Core.Domain.Solution", b =>
                {
                    b.HasOne("Trips.Core.Domain.OptimisationRun", null)
                        .WithMany("Solutions")
                        .HasForeignKey("OptimisationRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Core.Domain.Stop", b =>
                {
                    b.HasOne("Trips.Core.Domain.DriverRoute", null)
                        .WithMany("Stops")
                        .HasForeignKey("DriverRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Trips.Core.Domain.DriverRoute", b =>
                {
                    b.Navigation("Stops");
                });

            modelBuilder.Entity("Trips.Core.Domain.OptimisationRun", b =>
                {
                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("Trips.Core.Domain.Participant", b =>
                {
                    b.Navigation("CandidateNodes");
                });

            modelBuilder.Entity("Trips.Core.Domain.Solution", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Trips.Core.Domain.Trip", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
